#!/bin/bash

#
# run services necessary for booting Porteus Kiosk over the network.
#



#
# Path to folder where Kiosk ISO is unpacked/mounted:
#
PXEDATA=/var/lib/kiosk/


#
# Server IP address:
#
IP=`hostname -I | awk '{print $1}'`
echo "Agent server (this machine) IP address .... $IP"


#
# update hosts file
#
sudo sed -i "/examserver/d" /etc/hosts
sudo echo "$IP    examserver" >> /etc/hosts


#
# disable firewall
#
sudo ufw disable 2>/dev/null



#
# add entry of dhcp-range in dnsmasq.conf
#
sudo sed -i '/^dhcp-range=.*$/d' /etc/dnsmasq.conf
a=`echo $IP|cut -d. -f1,2`;b=`echo ".0.0"`;sudo echo "dhcp-range=$a$b,proxy" >> /etc/dnsmasq.conf



#
# Port on which the HTTP daemon is listening:
#
PORT=8090



#
# Start the DHCP server and the TFTP server:
#
sudo systemctl stop systemd-resolved
sudo killall dnsmasq 2>/dev/null
sudo dnsmasq --enable-tftp --tftp-root=$PXEDATA/boot --dhcp-boot=pxelinux.0,"$IP",$IP --dhcp-range=$(echo $IP | cut -d. -f1-3).50,$(echo $IP | cut -d. -f1-3).250,infinite --log-dhcp



#
# Start the HTTP server:
#
sudo killall webfsd 2>/dev/null
sudo webfsd -i 0.0.0.0 -p $PORT -r $PXEDATA -u nobody -g nogroup


#
# Enable packet forwarding so pxe clients can connect to internet:
#
sudo echo 1 > /proc/sys/net/ipv4/ip_forward


#
# add entry in /var/lib/kiosk/boot/pxelinux.cfg/default
#
sudo sed -i '/^append/d' /var/lib/kiosk/boot/pxelinux.cfg/default
sudo echo "append initrd=initrd.xz,pxelinux.cfg/initrdpxe.xz quiet http_server=$IP:8090" >> /var/lib/kiosk/boot/pxelinux.cfg/default


#
# done
#
echo "PXE services for Porteus Kiosk should be started now."

