#!/bin/bash

#
# init
#
BASEDIR=/root/deploy-agent


#
# Path to folder where Kiosk ISO is unpacked/mounted:
#
PXEDATA=/var/lib/kiosk


#
# Server IP address:
#
IP=`hostname -I | awk '{print $1}'`
echo "Agent server (this machine) IP address .... $IP"


#
# update hosts file
#
sudo sed -i "/examserver/d" /etc/hosts
sudo echo "$IP    examserver" >> /etc/hosts


#
# disable firewall
#
sudo ufw disable 2>/dev/null


#
# restore original files with placeholder string for IP and port
#
sudo cp $BASEDIR/configs/dnsmasq.conf /etc/dnsmasq.conf
sudo cp $BASEDIR/grub/grub.cfg /var/lib/kiosk/boot/grub/grub.cfg



#
# Legacy PXE
#
sudo echo "dhcp-match=set:bios,option:client-arch,0"  >> /etc/dnsmasq.conf
sudo echo "dhcp-boot=tag:bios,pxelinux.0, $IP, $IP"  >> /etc/dnsmasq.conf


#
# add UEFI Entry
#
sudo echo "dhcp-match=set:efi32,option:client-arch,6" >> /etc/dnsmasq.conf
sudo echo "dhcp-boot=tag:efi32,bootx64.efi, $IP, $IP" >> /etc/dnsmasq.conf
sudo echo "dhcp-match=set:efibc,option:client-arch,7" >> /etc/dnsmasq.conf
sudo echo "dhcp-boot=tag:efibc,bootx64.efi, $IP, $IP" >> /etc/dnsmasq.conf
sudo echo "dhcp-match=set:efi64,option:client-arch,9" >> /etc/dnsmasq.conf
sudo echo "dhcp-boot=tag:efi64,bootx64.efi, $IP, $IP" >> /etc/dnsmasq.conf



#
# Port on which the HTTP daemon is listening:
#
PORT=443



#
# Start the DHCP server and the TFTP server:
#
sudo systemctl stop systemd-resolved
sudo killall dnsmasq 2>/dev/null
sudo dnsmasq \
	--enable-tftp \
	--tftp-root=$PXEDATA/boot \
	--dhcp-range=$(echo $IP | cut -d. -f1-2).200.1,$(echo $IP | cut -d. -f1-2).201.254,infinite \
	--log-dhcp



#
# Start the HTTP server:
#
sudo killall webfsd 2>/dev/null
sudo webfsd -i 0.0.0.0 -p $PORT -r $PXEDATA/ -u nobody -g nogroup


#
# Enable packet forwarding so pxe clients can connect to internet:
#
sudo echo 1 > /proc/sys/net/ipv4/ip_forward


#
# add entry in /var/lib/kiosk/boot/pxelinux.cfg/default and grub.cfg
#
sudo sed -i '/^append/d' /var/lib/kiosk/boot/pxelinux.cfg/default
sudo echo "append initrd=initrd.xz,pxelinux.cfg/initrdpxe.xz quiet http_server=$IP:$PORT examserver=$IP" >> /var/lib/kiosk/boot/pxelinux.cfg/default
sudo sed -i "s#AGENT_SERVER_IP_PORT#$IP:$PORT#g" /var/lib/kiosk/boot/grub/grub.cfg

#
# done
#
echo "PXE services for Porteus Kiosk should be started now."

